- menu_name: "Regulament"

- name: "Termeni si conditii"
  url: "/termeni-si-conditii/"
  title: "Termeni si conditii"

- name: "Politica de Confidentialitate"
  url: "/politica-de-confidentialitate/"
  title: "Politica de Confidentialitate"
